<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Middleware\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyDay.Application\MyDay.Application.csproj" />
    <ProjectReference Include="..\MyDay.Infrastructure\MyDay.Infrastructure.csproj" />
  </ItemGroup>

</Project>
