@echo off
echo Killing any process on port 5169...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :5169') do taskkill /PID %%a /F 2>nul

echo Starting Backend...
start "Backend" cmd /k "cd /d D:\MyProject\MyDay\backend\MyDay\MyDay.API && dotnet run --no-launch-browser --launch-profile https"

echo Starting Frontend...
start "Frontend" cmd /k "cd /d D:\MyProject\MyDay\frontend\myday-client && npm run dev -- --open false"

echo Waiting for servers to start...
timeout /t 5 /nobreak

echo Opening browser...
start "" "http://localhost:5173"