namespace MyDay.Domain.Entities;

// This class represents a User in our application
// Entity Framework will create a "Users" table from this class
public class User
{
    public int Id { get; set; }          // Unique ID, auto-generated by database
    public string Email { get; set; } = string.Empty;     // Login email
    public string PasswordHash { get; set; } = string.Empty; // Encrypted password
    public string FirstName { get; set; } = string.Empty; // User's first name
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow; // When account was created

    // Navigation properties - these connect User to their data
    // One user can have MANY todos, habits and goals
    public ICollection<Todo> Todos { get; set; } = new List<Todo>();
    public ICollection<Habit> Habits { get; set; } = new List<Habit>();
    public ICollection<Goal> Goals { get; set; } = new List<Goal>();
}